# MD004/ul-style Unordered list style
MD004: false

# MD010
MD010: false

# MD013 Line length
MD013: false

#MD029/ol-prefix Ordered list item prefix
MD029: false

# MD033 Inline HTML
MD033: false

# MD036/no-emphasis-as-heading/no-emphasis-as-header Emphasis used instead of a heading
MD036: false

MD041: false

# MD024
no-duplicate-heading:
  siblings_only: true