name: golangci-lint
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  golangci:
    name: Lint
    runs-on: macos-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make lint
