name: lint-checker-ci
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    type: [review_requested, ready_for_review]
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
      go: ${{ steps.filter.outputs.go }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: ./.github/actions/paths-filter
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            docs:
              - 'docs/**/*'
              - '*.md'
            go:
              - '*.go'
              - '**/*.go'
              - 'go.mod'
              - 'go.sum'
              - 'Makefile'
              - 'Dockerfile'
              - 'test/e2e/**/*'
              - 'conf/**'
              - 'utils/**'
              - ".github/**"

  run-test:
    needs: changes
    if: |
      (needs.changes.outputs.go == 'true')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go Env
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: run gofmt
        working-directory: ./
        run: |
          diffs=`gofmt -l .`
          if [[ -n $diffs ]]; then
              echo "Files are not formatted by gofmt:"
              echo $diffs
              exit 1
          fi
  markdownlint:
    needs: changes
    if: |
      (needs.changes.outputs.docs == 'true')
    name: 🍇 Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 🚀 Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install -g markdownlint-cli@0.32.2
      - run: markdownlint '**/*.md' --ignore node_modules --ignore CHANGELOG.md
  markdown-link-check:
    needs: changes
    if: |
      (needs.changes.outputs.docs == 'true')
    runs-on: ubuntu-latest
    name: Check Markdown links
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/markdown-link-check
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: 'link-check-config.json'
          folder-path: 'docs/'
          file-path: './README.md'
          max-depth: -1
          file-extension: ".md"
          check-modified-files-only: "no"